package pl.put.poznan.BuildingInfo.model;

import com.fasterxml.jackson.annotation.JsonView;
import pl.put.poznan.BuildingInfo.other.LocationView;

import java.util.List;
import java.util.ArrayList;

/**
 * <code>CompoundLocation</code> is a location that can store other objects that inherit <code>{@link Location}</code> as
 * children in a tree.
 *
 * @version %I% %D%
 */
public class CompoundLocation extends Location {
    /**
     * list containing direct children
     */
    private List<Location> children;

    /**
     * Constructs <code>CompoundLocation</code> with autogenerated unique id, empty string as the name and no children.
     */
    public CompoundLocation() {
        this("");
    }

    /**
     * Constructs <code>CompoundLocation</code> with autogenerated unique id, specified name and no children.
     * @param name name of the compound location
     */
    public CompoundLocation(String name) {
        this(name, new ArrayList<>());
    }

    /**
     * Constructs <code>CompoundLocation</code> with autogenerated unique id, specified name and specified children.
     * @param name      name of the compound location
     * @param children  direct children in a tree
     */
    public CompoundLocation(String name, List<Location> children) {
        super(name);
        this.children = children;
    }

    public void setChildren(List<Location> children) {
        this.children = children;
    }

    @JsonView(LocationView.All.class)
    public List<Location> getChildren() {
        return children;
    }

    @Override
    public int getArea() {
        return children.stream().map(Location::getArea).reduce(0, Integer::sum);
    }

    @Override
    public int getCube() {
        return children.stream().map(Location::getCube).reduce(0, Integer::sum);
    }

    @Override
    public float getHeating() {
        return children.stream().map(Location::getHeating).reduce(0f, Float::sum);
    }

    @Override
    public float getLighting() {
        return children.stream().map(Location::getLighting).reduce(0f, Float::sum);
    }

    @Override
    public String info() {
        return this.info("", true, true);
    }

    @Override
    protected String info(String indent, boolean last, boolean start) {
        String elbow = "└──";
        String pipe = "│  ";
        String tee = "├──";
        String blank = "   ";
        StringBuilder tree = new StringBuilder();

        tree.append(indent);

        if(!start) {
            tree.append(last ? elbow : tee);
        }

        tree.append("Id: ").append(id);

        if(!start) {
            indent += (last ? blank : pipe);
        }

        for(int i = 0; i < children.size(); i++) {
            tree.append("\n");
            tree.append(children.get(i).info(indent,i == children.size() - 1,false));
        }

        return tree.toString();
    }

    @Override
    public String allInfo() {
        return this.allInfo("", true, true);
    }

    @Override
    protected String allInfo(String indent, boolean last, boolean start) {
        String elbow = "└──";
        String pipe = "│  ";
        String tee = "├──";
        String blank = "   ";
        StringBuilder tree = new StringBuilder();

        tree.append(indent);

        if(!start) {
            tree.append(last ? elbow : tee);
        }

        tree.append("Id: ")
            .append(id)
            .append(" Name: ")
            .append(name);

        if(!start) {
            indent += (last ? blank : pipe);
        }

        for(int i = 0; i < children.size(); i++) {
            tree.append("\n");
            tree.append(children.get(i).allInfo(indent,i == children.size() - 1,false));
        }

        return tree.toString();
    }
}
