package pl.put.poznan.BuildingInfo.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import pl.put.poznan.BuildingInfo.other.LocationView;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * <code>Location</code> is abstract base class for all locations that should be represented as a tree.
 *
 * @version %I% %D%
 */
@JsonIgnoreProperties(value={ "id", "cube" }, ignoreUnknown = true, allowGetters = true)
public abstract class Location {
    /**
     * used for generating unique identifiers of locations in app
     */
    protected static final AtomicInteger counter = new AtomicInteger(0);
    /**
     * unique identifier of the location
     */
    protected int id;
    /**
     * name associated with the location
     */
    protected String name;

    /**
     * Constructs a new <code>location</code> with autogenerated unique id and empty string as the name.
     */
    public Location() {
        this("");
    }

    /**
     * Constructs a new <code>Location</code> with autogenerated unique id and specified name.
     * @param name the name of the location
     */
    public Location(String name) {
        this.id = counter.incrementAndGet();
        this.name = name;
    }

    @JsonView(LocationView.Basic.class)
    public int getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    @JsonView(LocationView.Basic.class)
    public String getName() {
        return name;
    }

    @JsonView(LocationView.Area.class)
    public abstract int getArea();

    @JsonView(LocationView.Cube.class)
    public abstract int getCube();

    public abstract float getHeating();

    /**
     * Calculates average heating energy of location by dividing heating energy of location by its cubature.
     * @return average heating energy, 0 if location cubature is 0
     */
    @JsonProperty("average heating energy")
    @JsonView(LocationView.Heating.class)
    public float calculateHeatingEnergy() {
        if (getCube() == 0) {
            return 0;
        }
        return getHeating() / getCube();
    }

    public abstract float getLighting();

    /**
     * Calculates average lighting power of location by dividing lighting power of location by its area.
     * @return average lighting power, 0 if location area is 0
     */
    @JsonProperty("average lighting power")
    @JsonView(LocationView.Lighting.class)
    public float calculateLightingPower() {
        if (getArea() == 0) {
            return 0f;
        }
        return getLighting() / getArea();
    }

    /**
     * Provide short information about location in tree format.
     * @return tree of information about location
     */
    public abstract String info();

    /**
     * Provide short information about location in tree format. All parameters should be provided by {@link #info()}
     * @param indent    string to represent level of depth in tree
     * @param last      is this location the last direct child of its parent
     * @param start     is this location the root of the tree
     * @return tree of information about location
     */
    protected abstract String info(String indent, boolean last, boolean start);

    /**
     * Provide all information about location in tree format.
     * @return tree of information about location
     */
    public abstract String allInfo();

    /**
     * Provide short information about location in tree format. All parameters should be provided by {@link #allInfo()}
     * @param indent    string to represent level of depth in tree
     * @param last      is this location the last direct child of its parent
     * @param start     is this location the root of the tree
     * @return tree of information about location
     */
    protected abstract String allInfo(String indent, boolean last, boolean start);
}
