package pl.put.poznan.BuildingInfo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import pl.put.poznan.BuildingInfo.other.LocationView;

/**
 * <code>Room</code> is a location that represents leaf in a tree of <code>{@link Location}</code> objects.
 *
 * @version %I% %D%
 */
public class Room extends Location{
    /**
     * height of the room, used to calculate cubature
     */
    private int height;
    /**
     * area of the room, used to calculate cubature
     */
    private int area;
    /**
     * cubature of the room
     */
    private int cube;
    /**
     * heating energy of the room
     */
    private float heating;
    /**
     * lighting power of the room
     */
    private int lighting;

    private double energyPrice;
    /**
     * Constructs a new <code>Room</code> with autogenerated unique id and empty string as the name. Other fields are
     * set to 0.
     */
    public Room() {
        this("");
    }

    /**
     * Constructs a new <code>Room</code> with autogenerated unique id and specified name. Other fields are set ot 0.
     * @param name name of the room
     */
    public Room(String name) {
        this(name, 0, 0, 0, 0);
    }

    /**
     * Constructs a new <code>Room</code> with autogenerated unique id and specified name, area, height, heating energy
     * and lighting power.
     * @param name      name of the room
     * @param area      area of the room
     * @param height    height of the room
     * @param heating   heating energy of the room
     * @param lighting  lighting power of the room
     */
    public Room(String name, int area, int height, float heating, int lighting) {
        super(name);
        this.area = area;
        this.height = height;
        this.cube = height * area;
        this.heating = heating;
        this.lighting = lighting;
    }

    @Override
    @JsonView({LocationView.Area.class, LocationView.All.class})
    public int getArea() {
        return area;
    }

    public void setArea(int area) {
        this.area = area;
        this.cube = height * area;
    }

    public void setHeight(int height) {
        this.height = height;
        this.cube = height * area;
    }

    @Override
    @JsonView({LocationView.Cube.class, LocationView.All.class})
    public int getCube() {
        return cube;
    }

    @Override
    @JsonProperty("heating")
    @JsonView(LocationView.All.class)
    public float getHeating() {
        return heating;
    }

    public void setHeating(float heating) {
        this.heating = heating;
    }

    @Override
    @JsonProperty("lighting")
    @JsonView(LocationView.All.class)
    public float getLighting() {
        return (float) lighting;
    }

    public void setLighting(int lighting) {
        this.lighting = lighting;
    }

    public void setEnergyPrice(double price) {
        energyPrice = price;
    }

    @Override
    public String info() {
        return this.info("", true, true);
    }

    @Override
    protected String info(String indent, boolean last, boolean start) {
        String elbow = "└──";
        String tee = "├──";

        if(!start) {
            indent += (last ? elbow : tee);
        }

        return indent + "Id: " + id;
    }

    @Override
    public String allInfo() {
        return this.allInfo("", true, true);
    }

    @Override
    protected String allInfo(String indent, boolean last, boolean start) {
        String elbow = "└──";
        String tee = "├──";

        if(!start) {
            indent += (last ? elbow : tee);
        }

        return indent
               + "Id: " + id
               + " Name: " + name
               + " Area: " + area
               + " Cube: " + cube
               + " Heating: " + heating
               + " Lighting: " + lighting;
    }
}
